fixed php error message
PHP Parse error:  syntax error, unexpected '=', expecting ')' in /srv/www/dev3.deckdev.com/cehs/sites/all/modules/custom/cehs_ts/cehs_ts.module on line 80
Drush command terminated abnormally due to an unrecoverable error.                                                                 [error]
Error: syntax error, unexpected '=', expecting ')' in
/srv/www/dev3.deckdev.com/cehs/sites/all/modules/custom/cehs_ts/cehs_ts.module, line 80